DISKVOLUME=COPY.II.REBOOT
SYSNAME=UTIL.SYSTEM

BUILDDIR=build
BUILDLOG=$(BUILDDIR)/log
BUILDDISK=$(BUILDDIR)/$(DISKVOLUME).po

# https://brutaldeluxe.fr/products/crossdevtools/merlin/
# https://github.com/lifepillar/homebrew-appleii/blob/HEAD/Formula/merlin32.rb
MERLINBIN=Merlin32
MERLINLIB=/opt/homebrew/opt/merlin32/lib
MERLIN=$(MERLINBIN) -V $(MERLINLIB)
POSTMERLIN = (mv "$(SRCDIR)/$(notdir $@)_S01_Segment1_Output.txt" "$(BUILDDIR)"/ && mv "$(SRCDIR)/$(notdir $@)_Symbols.txt" "$(BUILDDIR)"/)

# https://github.com/mach-kernel/cadius
CADIUS=cadius

# https://github.com/einar-saukas/ZX0
# note: -b flag to pack backwards
# you can also add a -q flag during development
# to do worse compression at a more reasonable speed
# (does not affect format, so unpacker still works)
ZX0=zx0 -b

# macro to compress file with ZX0 then transpose first 7 bytes to end of file
# (used for self-decompressing modules)
X7 = ($(ZX0) "$1" "$@" && dd if="$@" of="$@.HEAD" bs=1 count=7 && dd if="$@" of="$@.TAIL" bs=1 skip=7 && cat "$@.TAIL" "$@.HEAD" > "$@")

SRCDIR=src
SOURCES=$(wildcard src/*.S)
PRODOS=PRODOS
CLOCK=CLOCK
MMO=$(BUILDDIR)/MM.O
MMX7=$(BUILDDIR)/MM.X7
MMVARS=$(BUILDDIR)/MM.VARS.S
DZX0TURBOO=$(BUILDDIR)/DZX0TURBO.O
DZX0TURBOVARS=$(BUILDDIR)/DZX0TURBO.VARS.S
BOOTSEC33O=$(BUILDDIR)/BOOTSEC.33.O
BOOTSEC33VARS=$(BUILDDIR)/BOOTSEC.33.VARS.S
BOOTSECPROO=$(BUILDDIR)/BOOTSEC.PRO.O
BOOTSECPROVARS=$(BUILDDIR)/BOOTSEC.PRO.VARS.S
FILERO=$(BUILDDIR)/FILER.O
FILERX=$(BUILDDIR)/FILER.X
FILERVARS=$(BUILDDIR)/FILER.VARS.S
CATLN1O=$(BUILDDIR)/CATLN1.O
CATLN1X7=$(BUILDDIR)/CATLN1.X7
CATLN1VARS=$(BUILDDIR)/CATLN1.VARS.S
MATCHO=$(BUILDDIR)/MATCH.O
MATCHX7=$(BUILDDIR)/MATCH.X7
MATCHVARS=$(BUILDDIR)/MATCH.VARS.S
DODEVO=$(BUILDDIR)/DODEV.O
DODEVX7=$(BUILDDIR)/DODEV.X7
DODEVVARS=$(BUILDDIR)/DODEV.VARS.S
DDISKO=$(BUILDDIR)/DDISK.O
DDISKX7=$(BUILDDIR)/DDISK.X7
DDISKVARS=$(BUILDDIR)/DDISK.VARS.S
D1FILEO=$(BUILDDIR)/D1FILE.O
D1FILEX7=$(BUILDDIR)/D1FILE.X7
D1FILEVARS=$(BUILDDIR)/D1FILE.VARS.S
DOTREEO=$(BUILDDIR)/DOTREE.O
DOTREEX7=$(BUILDDIR)/DOTREE.X7
DOTREEVARS=$(BUILDDIR)/DOTREE.VARS.S
COPYO=$(BUILDDIR)/COPY.O
COPYX7=$(BUILDDIR)/COPY.X7
COPYVARS=$(BUILDDIR)/COPY.VARS.S
CATALOGO=$(BUILDDIR)/CATALOG.O
CATALOGX7=$(BUILDDIR)/CATALOG.X7
CATALOGVARS=$(BUILDDIR)/CATALOG.VARS.S
DELETEO=$(BUILDDIR)/DELETE.O
DELETEX7=$(BUILDDIR)/DELETE.X7
DELETEVARS=$(BUILDDIR)/DELETE.VARS.S
ALPHABETIZEO=$(BUILDDIR)/ALPHABETIZE.O
ALPHABETIZEX7=$(BUILDDIR)/ALPHABETIZE.X7
ALPHABETIZEVARS=$(BUILDDIR)/ALPHABETIZE.VARS.S
FORMATO=$(BUILDDIR)/FORMAT.O
FORMATX7=$(BUILDDIR)/FORMAT.X7
FORMATVARS=$(BUILDDIR)/FORMAT.VARS.S
VERIFYO=$(BUILDDIR)/VERIFY.O
VERIFYX7=$(BUILDDIR)/VERIFY.X7
VERIFYVARS=$(BUILDDIR)/VERIFY.VARS.S
VIEWO=$(BUILDDIR)/VIEW.O
VIEWX7=$(BUILDDIR)/VIEW.X7
VIEWVARS=$(BUILDDIR)/VIEW.VARS.S
DISKMAPO=$(BUILDDIR)/DISKMAP.O
DISKMAPX7=$(BUILDDIR)/DISKMAP.X7
DISKMAPVARS=$(BUILDDIR)/DISKMAP.VARS.S
CHANGEBOOTO=$(BUILDDIR)/CHANGEBOOT.O
CHANGEBOOTX7=$(BUILDDIR)/CHANGEBOOT.X7
CHANGEBOOTVARS=$(BUILDDIR)/CHANGEBOOT.VARS.S
UNDELETEO=$(BUILDDIR)/UNDELETE.O
UNDELETEX7=$(BUILDDIR)/UNDELETE.X7
UNDELETEVARS=$(BUILDDIR)/UNDELETE.VARS.S
MAKESUBO=$(BUILDDIR)/MAKESUB.O
MAKESUBX7=$(BUILDDIR)/MAKESUB.X7
MAKESUBVARS=$(BUILDDIR)/MAKESUB.VARS.S
QUITO=$(BUILDDIR)/QUIT.O
QUITX7=$(BUILDDIR)/QUIT.X7
QUITVARS=$(BUILDDIR)/QUIT.VARS.S
SETCLOCKO=$(BUILDDIR)/SETCLOCK.O
SETCLOCKX=$(BUILDDIR)/SETCLOCK.X
SETCLOCKVARS=$(BUILDDIR)/SETCLOCK.VARS.S
EXE=$(BUILDDIR)/$(SYSNAME)
VARS = (awk -F';' '$1 { printf "%s EQU %s\n", $$6, $$5 }' < "$2_Symbols.txt" | grep -v "_" | sed -e "s/00\//\$$/g" > "$@")

.PHONY: clean mount all

$(EXE): $(MMX7) $(FILERX) $(CATLN1X7) $(MATCHX7) $(DODEVX7) $(DDISKX7) $(D1FILEX7) $(DOTREEX7) $(COPYX7) $(CATALOGX7) $(DELETEX7) $(ALPHABETIZEX7) $(FORMATX7) $(VERIFYX7) $(VIEWX7) $(DISKMAPX7) $(CHANGEBOOTX7) $(UNDELETEX7) $(MAKESUBX7) $(QUITX7) $(SETCLOCKX) $(MMVARS) $(FILERVARS) $(CATLN1VARS) $(MATCHVARS) $(DODEVVARS) $(DDISKVARS) $(D1FILEVARS) $(DOTREEVARS) $(COPYVARS) $(CATALOGVARS) $(DELETEVARS) $(ALPHABETIZEVARS) $(FORMATVARS) $(VERIFYVARS) $(VIEWVARS) $(DISKMAPVARS) $(CHANGEBOOTVARS) $(UNDELETEVARS) $(MAKESUBVARS) $(QUITVARS) $(SETCLOCKVARS) $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/CII.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(BUILDDISK): $(PRODOS) $(CLOCK) $(EXE)
	$(CADIUS) REPLACEFILE "$(BUILDDISK)" "/$(DISKVOLUME)/" "$(EXE)" -C
	$(CADIUS) CREATEFOLDER "$(BUILDDISK)" "/$(DISKVOLUME)/SUB1/" -C
	$(CADIUS) CREATEFOLDER "$(BUILDDISK)" "/$(DISKVOLUME)/SUB2/" -C
	$(CADIUS) CREATEFOLDER "$(BUILDDISK)" "/$(DISKVOLUME)/SUB2/SUBSUB1/" -C
	$(CADIUS) CREATEFOLDER "$(BUILDDISK)" "/$(DISKVOLUME)/SUB2/SUBSUB2/" -C
	$(CADIUS) CREATEFOLDER "$(BUILDDISK)" "/$(DISKVOLUME)/SUB3/" -C

#
# Memory Manager module (self-contained)(compressed)
#
$(MMO): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/MM.CII.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MMX7): $(MMO)
	$(call X7,$(MMO))

$(MMVARS): $(MMO)
	$(call VARS,/;MM.CII.S;/,$(MMO))

#
# ZX0 unpacker module (self-contained)(not compressed)
#
$(DZX0TURBOO): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/DZX0TURBO.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DZX0TURBOVARS): $(DZX0TURBOO)
	$(call VARS,/;DZX0TURBO.S;/,$(DZX0TURBOO))

#
# DOS 3.3 Boot Sector module
#
$(BOOTSEC33O): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/BOOTSEC.33.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(BOOTSEC33VARS): $(BOOTSEC33O)
	$(call VARS,/;BOOTSEC.33.S;/,$(BOOTSEC33O))

#
# ProDOS Boot Sector module
#
$(BOOTSECPROO): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/BOOTSEC.PRO.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(BOOTSECPROVARS): $(BOOTSECPROO)
	$(call VARS,/;BOOTSEC.PRO.S;/,$(BOOTSECPROO))

#
# Filer (requires Memory Manager, DOS 3.3 Boot Sector)(compressed)
#
$(FILERO): $(MMVARS) $(BOOTSEC33VARS)
	$(MERLIN) "$(SRCDIR)"/FILER.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(FILERVARS): $(FILERO)
	$(call VARS,!/;VARS;/,$(FILERO))

$(FILERX): $(FILERO)
	$(ZX0) "$(FILERO)" "$@"

#
# Catalog Show Line module (requires Filer)(compressed)(self-decompressing)
#
$(CATLN1O): $(FILERVARS)
	$(MERLIN) "$(SRCDIR)"/CATLN1.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(CATLN1VARS): $(CATLN1O)
	$(call VARS,/;CATLN1.S;/,$(CATLN1O))

$(CATLN1X7): $(CATLN1O)
	$(call X7,$(CATLN1O))

#
# Pattern Match module (requires Filer)(compressed)(self-decompressing)
#
$(MATCHO): $(FILERVARS) $(CATLN1VARS)
	$(MERLIN) "$(SRCDIR)"/MATCH.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MATCHVARS): $(MATCHO)
	$(call VARS,/;MATCH.S;/,$(MATCHO))

$(MATCHX7): $(MATCHO)
	$(call X7,$(MATCHO))

#
# DoDev module (requires Filer)(compressed)(self-decompressing)
#
$(DODEVO): $(FILERVARS) $(MATCHVARS)
	$(MERLIN) "$(SRCDIR)"/DODEV.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DODEVVARS): $(DODEVO)
	$(call VARS,/;DODEV.S;/,$(DODEVO))

$(DODEVX7): $(DODEVO)
	$(call X7,$(DODEVO))

#
# DDisk module (requires Filer, ProDOS Boot Sector)(compressed)(self-decompressing)
#
$(DDISKO): $(FILERVARS) $(BOOTSECPROVARS) $(DODEVVARS)
	$(MERLIN) "$(SRCDIR)"/DDISK.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DDISKVARS): $(DDISKO)
	$(call VARS,/;DDISK.S;/,$(DDISKO))

$(DDISKX7): $(DDISKO)
	$(call X7,$(DDISKO))

#
# D1File module (requires Filer)(compressed)(self-decompressing)
#
$(D1FILEO): $(FILERVARS) $(DDISKVARS)
	$(MERLIN) "$(SRCDIR)"/D1FILE.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(D1FILEVARS): $(D1FILEO)
	$(call VARS,/;D1FILE.S;/,$(D1FILEO))

$(D1FILEX7): $(D1FILEO)
	$(call X7,$(D1FILEO))

#
# DoTree module (requires Filer)(compressed)(self-decompressing)
#
$(DOTREEO): $(FILERVARS) $(D1FILEVARS)
	$(MERLIN) "$(SRCDIR)"/DOTREE.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DOTREEVARS): $(DOTREEO)
	$(call VARS,/;DOTREE.S;/,$(DOTREEO))

$(DOTREEX7): $(DOTREEO)
	$(call X7,$(DOTREEO))

#
# Copy module (requires Filer)(compressed)(self-decompressing)
#
$(COPYO): $(FILERVARS) $(MMVARS) $(DOTREEVARS)
	$(MERLIN) "$(SRCDIR)"/COPY.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(COPYVARS): $(COPYO)
	$(call VARS,/;COPY.S;/,$(COPYO))

$(COPYX7): $(COPYO)
	$(call X7,$(COPYO))

#
# Catalog module (requires Filer)(compressed)(self-decompressing)
#
$(CATALOGO): $(FILERVARS) $(COPYVARS)
	$(MERLIN) "$(SRCDIR)"/CATALOG.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(CATALOGVARS): $(CATALOGO)
	$(call VARS,/;CATALOG.S;/,$(CATALOGO))

$(CATALOGX7): $(CATALOGO)
	$(call X7,$(CATALOGO))

#
# Delete module (requires Filer)(compressed)(self-decompressing)
#
$(DELETEO): $(FILERVARS) $(CATALOGVARS)
	$(MERLIN) "$(SRCDIR)"/DELETE.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DELETEVARS): $(DELETEO)
	$(call VARS,/;DELETE.S;/,$(DELETEO))

$(DELETEX7): $(DELETEO)
	$(call X7,$(DELETEO))

#
# Alphabetize Catalog module (requires Filer)(compressed)(self-decompressing)
#
$(ALPHABETIZEO): $(FILERVARS) $(DELETEVARS)
	$(MERLIN) "$(SRCDIR)"/ALPHABETIZE.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(ALPHABETIZEVARS): $(ALPHABETIZEO)
	$(call VARS,/;ALPHABETIZE.S;/,$(ALPHABETIZEO))

$(ALPHABETIZEX7): $(ALPHABETIZEO)
	$(call X7,$(ALPHABETIZEO))

#
# Format module (requires Filer)(compressed)(self-decompressing)
#
$(FORMATO): $(FILERVARS) $(ALPHABETIZEVARS)
	$(MERLIN) "$(SRCDIR)"/FORMAT.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(FORMATVARS): $(FORMATO)
	$(call VARS,/;FORMAT.S;/,$(FORMATO))

$(FORMATX7): $(FORMATO)
	$(call X7,$(FORMATO))

#
# Verify module (requires Filer)(compressed)(self-decompressing)
#
$(VERIFYO): $(FILERVARS) $(FORMATVARS)
	$(MERLIN) "$(SRCDIR)"/VERIFY.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(VERIFYVARS): $(VERIFYO)
	$(call VARS,/;VERIFY.S;/,$(VERIFYO))

$(VERIFYX7): $(VERIFYO)
	$(call X7,$(VERIFYO))

#
# View module (requires Filer)(compressed)(self-decompressing)
#
$(VIEWO): $(FILERVARS) $(VERIFYVARS)
	$(MERLIN) "$(SRCDIR)"/VIEW.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(VIEWVARS): $(VIEWO)
	$(call VARS,/;VIEW.S;/,$(VIEWO))

$(VIEWX7): $(VIEWO)
	$(call X7,$(VIEWO))

#
# Disk Map module (requires Filer)(compressed)(self-decompressing)
#
$(DISKMAPO): $(FILERVARS) $(VIEWVARS)
	$(MERLIN) "$(SRCDIR)"/DISKMAP.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DISKMAPVARS): $(DISKMAPO)
	$(call VARS,/;DISKMAP.S;/,$(DISKMAPO))

$(DISKMAPX7): $(DISKMAPO)
	$(call X7,$(DISKMAPO))

#
# Change Boot Program module (requires Filer)(compressed)(self-decompressing)
#
$(CHANGEBOOTO): $(FILERVARS) $(DISKMAPVARS)
	$(MERLIN) "$(SRCDIR)"/CHANGEBOOT.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(CHANGEBOOTVARS): $(CHANGEBOOTO)
	$(call VARS,/;CHANGEBOOT.S;/,$(CHANGEBOOTO))

$(CHANGEBOOTX7): $(CHANGEBOOTO)
	$(call X7,$(CHANGEBOOTO))

#
# Undelete module (requires Filer)(compressed)(self-decompressing)
#
$(UNDELETEO): $(FILERVARS) $(CHANGEBOOTVARS)
	$(MERLIN) "$(SRCDIR)"/UNDELETE.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(UNDELETEVARS): $(UNDELETEO)
	$(call VARS,/;UNDELETE.S;/,$(UNDELETEO))

$(UNDELETEX7): $(UNDELETEO)
	$(call X7,$(UNDELETEO))

#
# Create Subdirectory module (requires Filer)(compressed)(self-decompressing)
#
$(MAKESUBO): $(FILERVARS) $(UNDELETEVARS)
	$(MERLIN) "$(SRCDIR)"/MAKESUB.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MAKESUBVARS): $(MAKESUBO)
	$(call VARS,/;MAKESUB.S;/,$(MAKESUBO))

$(MAKESUBX7): $(MAKESUBO)
	$(call X7,$(MAKESUBO))

#
# Quit module (requires Filer)(compressed)(self-decompressing)
#
$(QUITO): $(FILERVARS) $(MAKESUBVARS)
	$(MERLIN) "$(SRCDIR)"/QUIT.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(QUITVARS): $(QUITO)
	$(call VARS,/;QUIT.S;/,$(QUITO))

$(QUITX7): $(QUITO)
	$(call X7,$(QUITO))

#
# Set Clock (requires Filer)(compressed)
#
$(SETCLOCKO): $(FILERVARS)
	$(MERLIN) "$(SRCDIR)"/SETCLOCK.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(SETCLOCKX): $(SETCLOCKO)
	$(ZX0) "$(SETCLOCKO)" "$@"

$(SETCLOCKVARS): $(SETCLOCKO)
	$(call VARS,/;SETCLOCK.S;/,$(SETCLOCKO))

# things that go in the root directory
$(PRODOS) $(CLOCK): $(BUILDDIR)
	$(CADIUS) ADDFOLDER "$(BUILDDISK)" "/$(DISKVOLUME)/" "$@" -C

mount: $(BUILDDISK)
	@open "$(BUILDDISK)"

clean:
	rm -rf "$(BUILDDIR)"

$(BUILDDIR):
	mkdir -p "$@"
	touch "$(BUILDLOG)"
	$(CADIUS) CREATEVOLUME "$(BUILDDISK)" "$(DISKVOLUME)" 140KB -C

all: clean mount

.NOTPARALLEL:
