DISKVOLUME=COPY.II.REBOOT
SYSNAME=UTIL.SYSTEM

BUILDDIR=build
BUILDLOG=$(BUILDDIR)/log
BUILDDISK=$(BUILDDIR)/$(DISKVOLUME).po

# https://brutaldeluxe.fr/products/crossdevtools/merlin/
# https://github.com/lifepillar/homebrew-appleii/blob/HEAD/Formula/merlin32.rb
MERLINBIN=Merlin32
MERLINLIB=/opt/homebrew/opt/merlin32/lib
MERLIN=$(MERLINBIN) -V $(MERLINLIB)
POSTMERLIN = (mv "$(SRCDIR)/$(notdir $@)_S01_Segment1_Output.txt" "$(BUILDDIR)"/ && mv "$(SRCDIR)/$(notdir $@)_Symbols.txt" "$(BUILDDIR)"/)

# https://github.com/mach-kernel/cadius
CADIUS=cadius

# https://github.com/einar-saukas/ZX0
# note: -b flag to pack backwards
# you can also add a -q flag during development
# to do worse compression at a more reasonable speed
# (does not affect format, so unpacker still works)
ZX0=zx0 -b

# macro to compress file with ZX0 then transpose first 7 bytes to end of file
# (used for self-decompressing modules)
X7 = ($(ZX0) "$1" "$@" && dd if="$@" of="$@.HEAD" bs=1 count=7 && dd if="$@" of="$@.TAIL" bs=1 skip=7 && cat "$@.TAIL" "$@.HEAD" > "$@")

SRCDIR=src
SOURCES=$(wildcard src/*.S)
MMO=$(BUILDDIR)/MM.O
MMX7=$(BUILDDIR)/MM.X7
MMVARS=$(BUILDDIR)/MM.VARS.S
DZX0TURBOO=$(BUILDDIR)/DZX0TURBO.O
DZX0TURBOVARS=$(BUILDDIR)/DZX0TURBO.VARS.S
BOOTSEC33O=$(BUILDDIR)/BOOTSEC.33.O
BOOTSEC33VARS=$(BUILDDIR)/BOOTSEC.33.VARS.S
BOOTSECPROO=$(BUILDDIR)/BOOTSEC.PRO.O
BOOTSECPROVARS=$(BUILDDIR)/BOOTSEC.PRO.VARS.S
PHRWTSO=$(BUILDDIR)/PHRWTS.O
PHRWTSX7=$(BUILDDIR)/PHRWTS.X7
PHRWTSVARS=$(BUILDDIR)/PHRWTS.VARS.S
MESSAGES2O=$(BUILDDIR)/MESSAGES2.O
MESSAGES2X7=$(BUILDDIR)/MESSAGES2.X7
MESSAGES2VARS=$(BUILDDIR)/MESSAGES2.VARS.S
MESSAGESO=$(BUILDDIR)/MESSAGES.O
MESSAGESVARS=$(BUILDDIR)/MESSAGES.VARS.S
DRIVE35O=$(BUILDDIR)/DRIVE35.O
DRIVE35VARS=$(BUILDDIR)/DRIVE35.VARS.S
PRODOSO=$(BUILDDIR)/PRODOS.O
PRODOSVARS=$(BUILDDIR)/PRODOS.VARS.S
IOO=$(BUILDDIR)/IO.O
IOVARS=$(BUILDDIR)/IO.VARS.S
ERRORSO=$(BUILDDIR)/ERRORS.O
ERRORSVARS=$(BUILDDIR)/ERRORS.VARS.S
LINEINPUTO=$(BUILDDIR)/LINEINPUT.O
LINEINPUTVARS=$(BUILDDIR)/LINEINPUT.VARS.S
UILIBO=$(BUILDDIR)/UILIB.O
UILIBVARS=$(BUILDDIR)/UILIB.VARS.S
READLIBO=$(BUILDDIR)/READLIB.O
READLIBVARS=$(BUILDDIR)/READLIB.VARS.S
DISKLIBO=$(BUILDDIR)/DISKLIB.O
DISKLIBVARS=$(BUILDDIR)/DISKLIB.VARS.S
TREELIBO=$(BUILDDIR)/TREELIB.O
TREELIBX7=$(BUILDDIR)/TREELIB.X7
TREELIBVARS=$(BUILDDIR)/TREELIB.VARS.S
MENUO=$(BUILDDIR)/MENU.O
MENUVARS=$(BUILDDIR)/MENU.VARS.S
FILERO=$(BUILDDIR)/FILER.O
FILERX=$(BUILDDIR)/FILER.X
FILERVARS=$(BUILDDIR)/FILER.VARS.S
CATLIBO=$(BUILDDIR)/CATLIB.O
CATLIBX7=$(BUILDDIR)/CATLIB.X7
CATLIBVARS=$(BUILDDIR)/CATLIB.VARS.S
COPYO=$(BUILDDIR)/COPY.O
COPYX7=$(BUILDDIR)/COPY.X7
COPYVARS=$(BUILDDIR)/COPY.VARS.S
CATALOGO=$(BUILDDIR)/CATALOG.O
CATALOGX7=$(BUILDDIR)/CATALOG.X7
CATALOGVARS=$(BUILDDIR)/CATALOG.VARS.S
DELLIBO=$(BUILDDIR)/DELLIB.O
DELLIBX7=$(BUILDDIR)/DELLIB.X7
DELLIBVARS=$(BUILDDIR)/DELLIB.VARS.S
VERIFYO=$(BUILDDIR)/VERIFY.O
VERIFYX7=$(BUILDDIR)/VERIFY.X7
VERIFYVARS=$(BUILDDIR)/VERIFY.VARS.S
DISKMAPO=$(BUILDDIR)/DISKMAP.O
DISKMAPX7=$(BUILDDIR)/DISKMAP.X7
DISKMAPVARS=$(BUILDDIR)/DISKMAP.VARS.S
UNDELETEO=$(BUILDDIR)/UNDELETE.O
UNDELETEX7=$(BUILDDIR)/UNDELETE.X7
UNDELETEVARS=$(BUILDDIR)/UNDELETE.VARS.S
MISCLIBO=$(BUILDDIR)/MISCLIB.O
MISCLIBX7=$(BUILDDIR)/MISCLIB.X7
MISCLIBVARS=$(BUILDDIR)/MISCLIB.VARS.S
EXE=$(BUILDDIR)/$(SYSNAME)
PRODOS=res/PRODOS\#FF0000
MANUAL=$(BUILDDIR)/REBOOT.MANUAL\#040000
VARS = (awk -F';' '$1 { printf "%s EQU %s\n", $$6, $$5 }' < "$2_Symbols.txt" | grep -v "_" | grep -v "Name EQU Address" | sed -e "s/00\//\$$/g" > "$@")

.PHONY: clean mount all

$(EXE): $(MMX7) $(PHRWTSX7) $(MESSAGES2X7) $(FILERX) $(TREELIBX7) $(CATLIBX7) $(COPYX7) $(CATALOGX7) $(DELLIBX7) $(VERIFYX7) $(DISKMAPX7) $(UNDELETEX7) $(MISCLIBX7) $(MMVARS) $(PHRWTSVARS) $(READLIBVARS) $(FILERVARS) $(TREELIBVARS) $(CATLIBVARS) $(COPYVARS) $(CATALOGVARS) $(DELLIBVARS) $(VERIFYVARS) $(DISKMAPVARS) $(UNDELETEVARS) $(MISCLIBVARS) $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/CII.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MANUAL): $(BUILDDIR)
	tr "\n" "\r" < docs/manual.txt > "$(MANUAL)"

$(BUILDDISK): $(EXE) $(MANUAL)
	$(CADIUS) REPLACEFILE "$(BUILDDISK)" "/$(DISKVOLUME)/" "$(PRODOS)" -C
	$(CADIUS) REPLACEFILE "$(BUILDDISK)" "/$(DISKVOLUME)/" "$(EXE)" -C
	$(CADIUS) REPLACEFILE "$(BUILDDISK)" "/$(DISKVOLUME)/" "$(MANUAL)" -C

#
# Memory Manager module (self-contained)(compressed)
#
$(MMO): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/MM.CII.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MMX7): $(MMO)
	$(call X7,$(MMO))

$(MMVARS): $(MMO)
	$(call VARS,/;MM.CII.S;/,$(MMO))

#
# ZX0 unpacker module (self-contained)(not compressed)
#
$(DZX0TURBOO): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/DZX0TURBO.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DZX0TURBOVARS): $(DZX0TURBOO)
	$(call VARS,/;DZX0TURBO.S;/,$(DZX0TURBOO))

#
# DOS 3.3 Boot Sector module
#
$(BOOTSEC33O): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/BOOTSEC.33.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(BOOTSEC33VARS): $(BOOTSEC33O)
	$(call VARS,/;BOOTSEC.33.S;/,$(BOOTSEC33O))

#
# ProDOS Boot Sector module
#
$(BOOTSECPROO): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/BOOTSEC.PRO.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(BOOTSECPROVARS): $(BOOTSECPROO)
	$(call VARS,/;BOOTSEC.PRO.S;/,$(BOOTSECPROO))

#
# PHRWTS module (compressed)(self-decompressing)
#
$(PHRWTSO): $(BUILDDIR)
	$(MERLIN) "$(SRCDIR)"/PHRWTS.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(PHRWTSVARS): $(PHRWTSO)
	$(call VARS,/;PHRWTS.S;/,$(PHRWTSO))

$(PHRWTSX7): $(PHRWTSO)
	$(call X7,$(PHRWTSO))

#
# MESSAGES2 module (compressed)(self-decompressing)
# contains less-common message strings
#
$(MESSAGES2O): $(PHRWTSVARS)
	$(MERLIN) "$(SRCDIR)"/MESSAGES2.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MESSAGES2VARS): $(MESSAGES2O)
	$(call VARS,/;MESSAGES2.S;/,$(MESSAGES2O))

$(MESSAGES2X7): $(MESSAGES2O)
	$(call X7,$(MESSAGES2O))

#
# MESSAGES module
# contains message strings
#
$(MESSAGESO): $(MESSAGES2VARS)
	$(MERLIN) "$(SRCDIR)"/MESSAGES.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MESSAGESVARS): $(MESSAGESO)
	$(call VARS,/;MESSAGES.S;/,$(MESSAGESO))

#
# DRIVE35 module
# contains low-level hardware routines for 3.5-inch drives
#
$(DRIVE35O): $(MESSAGESVARS)
	$(MERLIN) "$(SRCDIR)"/DRIVE35.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DRIVE35VARS): $(DRIVE35O)
	$(call VARS,!/;VARS;/,$(DRIVE35O))

#
# PRODOS module
# contains low-level ProDOS routines
#
$(PRODOSO): $(DRIVE35VARS)
	$(MERLIN) "$(SRCDIR)"/PRODOS.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(PRODOSVARS): $(PRODOSO)
	$(call VARS,!/;VARS;/,$(PRODOSO))

#
# I/O module
# contains low-level text handling routines
#
$(IOO): $(MESSAGES2VARS) $(MESSAGESVARS) $(PRODOSVARS)
	$(MERLIN) "$(SRCDIR)"/IO.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(IOVARS): $(IOO)
	$(call VARS,!/;VARS;/,$(IOO))

#
# ERRORS
# contains error handling routines
#
$(ERRORSO): $(IOVARS) $(LINEINPUTVARS)
	$(MERLIN) "$(SRCDIR)"/ERRORS.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(ERRORSVARS): $(ERRORSO)
	$(call VARS,!/;VARS;/,$(ERRORSO))

#
# LINEINPUT module
# contains text input handling routines
#
$(LINEINPUTO): $(IOVARS) $(MENUVARS)
	$(MERLIN) "$(SRCDIR)"/LINEINPUT.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(LINEINPUTVARS): $(LINEINPUTO)
	$(call VARS,!/;VARS;/,$(LINEINPUTO))

#
# MENU module
# contains main menu and submenu routines
#
$(MENUO): $(MMVARS) $(DRIVE35VARS) $(PRODOSVARS) $(IOVARS)
	$(MERLIN) "$(SRCDIR)"/MENU.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MENUVARS): $(MENUO)
	$(call VARS,!/;VARS;/,$(MENUO))

#
# UILIB module
# contains higher-level text routines
#
$(UILIBO): $(PRODOSVARS) $(IOVARS) $(ERRORSVARS)
	$(MERLIN) "$(SRCDIR)"/UILIB.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(UILIBVARS): $(UILIBO)
	$(call VARS,!/;VARS;/,$(UILIBO))

#
# DISKLIB module
#
$(DISKLIBO): $(PHRWTSVARS) $(PRODOSVARS) $(IOVARS) $(ERRORSVARS) $(READLIBVARS)
	$(MERLIN) "$(SRCDIR)"/DISKLIB.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DISKLIBVARS): $(DISKLIBO)
	$(call VARS,!/;VARS;/,$(DISKLIBO))

#
# TREELIB module (compressed)(self-decompressing)
#
$(TREELIBO): $(PHRWTSVARS) $(IOVARS) $(ERRORSVARS) $(UILIBVARS) $(DISKLIBVARS)
	$(MERLIN) "$(SRCDIR)"/TREELIB.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(TREELIBVARS): $(TREELIBO)
	$(call VARS,!/;VARS;/,$(TREELIBO))

$(TREELIBX7): $(TREELIBO)
	$(call X7,$(TREELIBO))

#
# Filer (compressed)
#
$(FILERO): $(BOOTSEC33VARS) $(PHRWTSVARS) $(MESSAGES2VARS) $(MESSAGESVARS) $(DRIVE35VARS) $(PRODOSVARS) $(IOVARS) $(MENUVARS) $(ERRORSVARS) $(LINEINPUTVARS) $(UILIBVARS) $(READLIBVARS) $(DISKLIBVARS) $(TREELIBVARS)
	$(MERLIN) "$(SRCDIR)"/FILER.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(FILERVARS): $(FILERO)
	$(call VARS,!/;VARS;/,$(FILERO))

$(FILERX): $(FILERO)
	$(ZX0) "$(FILERO)" "$@"

#
# READLIB module
# File-reading routines
#
$(READLIBO): $(PHRWTSVARS) $(PRODOSVARS) $(IOVARS) $(ERRORSVARS) $(UILIBVARS)
	$(MERLIN) "$(SRCDIR)"/READLIB.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(READLIBVARS): $(READLIBO)
	$(call VARS,/;READLIB.S;/,$(READLIBO))

#
# Catalog Library module (compressed)(self-decompressing)
#
$(CATLIBO): $(PHRWTSVARS) $(PRODOSVARS) $(IOVARS) $(LINEINPUTVARS) $(ERRORSVARS) $(UILIBVARS) $(READLIBVARS) $(DISKLIBVARS) $(TREELIBVARS)
	$(MERLIN) "$(SRCDIR)"/CATLIB.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(CATLIBVARS): $(CATLIBO)
	$(call VARS,/;CATLIB.S;/,$(CATLIBO))

$(CATLIBX7): $(CATLIBO)
	$(call X7,$(CATLIBO))

#
# Copy module (compressed)(self-decompressing)
#
$(COPYO): $(PHRWTSVARS) $(DRIVE35VARS) $(PRODOSVARS) $(IOVARS) $(LINEINPUTVARS) $(ERRORSVARS) $(UILIBVARS) $(MMVARS) $(READLIBVARS) $(DISKLIBVARS) $(CATLIBVARS) $(TREELIBVARS) $(DELLIBVARS)
	$(MERLIN) "$(SRCDIR)"/COPY.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(COPYVARS): $(COPYO)
	$(call VARS,/;COPY.S;/,$(COPYO))

$(COPYX7): $(COPYO)
	$(call X7,$(COPYO))

#
# Catalog module (compressed)(self-decompressing)
#
$(CATALOGO): $(PRODOSVARS) $(IOVARS) $(ERRORSVARS) $(UILIBVARS) $(READLIBVARS) $(CATLIBVARS) $(TREELIBVARS) $(COPYVARS)
	$(MERLIN) "$(SRCDIR)"/CATALOG.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(CATALOGVARS): $(CATALOGO)
	$(call VARS,/;CATALOG.S;/,$(CATALOGO))

$(CATALOGX7): $(CATALOGO)
	$(call X7,$(CATALOGO))

#
# Delete module (compressed)(self-decompressing)
#
$(DELLIBO): $(BOOTSECPROVARS) $(PHRWTSVARS) $(PRODOSVARS) $(IOVARS) $(LINEINPUTVARS) $(ERRORSVARS) $(UILIBVARS) $(READLIBVARS) $(DISKLIBVARS) $(CATLIBVARS) $(TREELIBVARS)
	$(MERLIN) "$(SRCDIR)"/DELLIB.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DELLIBVARS): $(DELLIBO)
	$(call VARS,/;DELLIB.S;/,$(DELLIBO))

$(DELLIBX7): $(DELLIBO)
	$(call X7,$(DELLIBO))

#
# Verify module (compressed)(self-decompressing)
#
$(VERIFYO): $(PHRWTSVARS) $(PRODOSVARS) $(IOVARS) $(ERRORSVARS) $(UILIBVARS) $(READLIBVARS) $(DISKLIBVARS) $(CATLIBVARS) $(TREELIBVARS) $(CATALOGVARS)
	$(MERLIN) "$(SRCDIR)"/VERIFY.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(VERIFYVARS): $(VERIFYO)
	$(call VARS,/;VERIFY.S;/,$(VERIFYO))

$(VERIFYX7): $(VERIFYO)
	$(call X7,$(VERIFYO))

#
# Disk Map module (compressed)(self-decompressing)
#
$(DISKMAPO): $(PRODOSVARS) $(IOVARS) $(ERRORSVARS) $(UILIBVARS) $(READLIBVARS) $(DISKLIBVARS) $(CATLIBVARS) $(TREELIBVARS) $(VERIFYVARS)
	$(MERLIN) "$(SRCDIR)"/DISKMAP.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(DISKMAPVARS): $(DISKMAPO)
	$(call VARS,/;DISKMAP.S;/,$(DISKMAPO))

$(DISKMAPX7): $(DISKMAPO)
	$(call X7,$(DISKMAPO))

#
# Undelete module (compressed)(self-decompressing)
#
$(UNDELETEO): $(PRODOSVARS) $(IOVARS) $(ERRORSVARS) $(UILIBVARS) $(READLIBVARS) $(DISKLIBVARS) $(CATLIBVARS) $(TREELIBVARS) $(DISKMAPVARS)
	$(MERLIN) "$(SRCDIR)"/UNDELETE.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(UNDELETEVARS): $(UNDELETEO)
	$(call VARS,/;UNDELETE.S;/,$(UNDELETEO))

$(UNDELETEX7): $(UNDELETEO)
	$(call X7,$(UNDELETEO))

#
# Miscellaneous module (compressed)(self-decompressing)
# contains several less-common features like
# Make Subdirectory, Change Boot Program, Alphabetize Catalog, &c.
#
$(MISCLIBO): $(PRODOSVARS) $(IOVARS) $(LINEINPUTVARS) $(ERRORSVARS) $(UILIBVARS) $(READLIBVARS) $(DISKLIBVARS) $(CATLIBVARS) $(TREELIBVARS) $(UNDELETEVARS)
	$(MERLIN) "$(SRCDIR)"/MISCLIB.S > "$(BUILDLOG)"
	$(call POSTMERLIN)

$(MISCLIBVARS): $(MISCLIBO)
	$(call VARS,/;MISCLIB.S;/,$(MISCLIBO))

$(MISCLIBX7): $(MISCLIBO)
	$(call X7,$(MISCLIBO))

mount: $(BUILDDISK)
	@open "$(BUILDDISK)"

clean:
	rm -rf "$(BUILDDIR)"

$(BUILDDIR):
	mkdir -p "$@"
	touch "$(BUILDLOG)"
	$(CADIUS) CREATEVOLUME "$(BUILDDISK)" "$(DISKVOLUME)" 140KB -C

all: clean mount

.NOTPARALLEL:
