*
* Dispatch table for main menu
*
*label in VARS
*MENUTBL
            DW    COPY
            DW    CATALOG
            DW    DELETE
            DW    LOCK
            DW    RENAME
            DW    ALPHA
            DW    FORMAT
            DW    VERIFY
            DW    VIEW
            DW    TSMAP
            DW    BOOTPG
            DW    UNDEL
            DW    MAKEDR
            DW    SETPRINT
            DW    QUIT
            ERR   *-MENUTBL-MENUTSZ
